//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           6.1.0-build.78+g20c58b7023
//       
//       Command:
//           LottieGen -Interface ILottieVisual -Language CSharp -InputFile heart.json
//       
//       Input file:
//           heart.json (15008 bytes created 15:51-07:00 Jun 30 2020)
//       
//       Invoked on:
//           KAREN @ 15:51-07:00 Jun 30 2020
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   230 |
// |--------------------------+-------|
// | Animators                |    70 |
// | Animated brushes         |    10 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |    10 |
// | CompositionSpriteShapes  |    10 |
// |--------------------------+-------|
// | Brushes                  |    10 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedIconPrototype
{
    // Name:        heart-pop-animation
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    sealed class Heart : ILottieVisualSource
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Theme property: Foreground.
        internal static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);

        CompositionPropertySet _themeProperties;
        Color _themeForeground = c_themeForeground;

        // Theme properties.
        public Color Foreground
        {
            get => _themeForeground;
            set
            {
                _themeForeground = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)_themeForeground));
                }
            }
        }

        public CompositionPropertySet GetThemeProperties(Compositor compositor)
        {
            return EnsureThemeProperties(compositor);
        }

        internal static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties is null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)Foreground));
            }
            return _themeProperties;
        }

        public ILottieVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            if (AnimatedVisual.IsRuntimeCompatible())
            {
                return
                    new AnimatedVisual(
                        compositor
                        );
            }

            return null;
        }

        sealed class AnimatedVisual : ILottieVisual
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionEllipseGeometry _ellipse_5p077;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            ColorKeyFrameAnimation CreateColorKeyFrameAnimation(float initialProgress, Color initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InterpolationColorSpace = CompositionColorSpace.Rgb;
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Group 1 Offset:<63, 62.263>
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(21.7789993F, -19.1429996F));
                    builder.AddCubicBezier(new Vector2(15.9779997F, -23.9950008F), new Vector2(7.43499994F, -23.2560005F), new Vector2(2.05599999F, -17.6669998F));
                    builder.AddLine(new Vector2(0.0529999994F, -15.5570002F));
                    builder.AddLine(new Vector2(-2.05699992F, -17.6669998F));
                    builder.AddCubicBezier(new Vector2(-6.38100004F, -22.0960007F), new Vector2(-15.0299997F, -24.8379993F), new Vector2(-21.7800007F, -19.1429996F));
                    builder.AddCubicBezier(new Vector2(-28.4239998F, -13.448F), new Vector2(-28.7399998F, -3.32299995F), new Vector2(-22.8339996F, 2.79399991F));
                    builder.AddLine(new Vector2(-2.37299991F, 23.8889999F));
                    builder.AddCubicBezier(new Vector2(-1.74000001F, 24.5209999F), new Vector2(-0.897000015F, 24.8369999F), new Vector2(-0.0529999994F, 24.8369999F));
                    builder.AddCubicBezier(new Vector2(0.896000028F, 24.8369999F), new Vector2(1.74000001F, 24.5209999F), new Vector2(2.37299991F, 23.8889999F));
                    builder.AddLine(new Vector2(22.8339996F, 2.79399991F));
                    builder.AddCubicBezier(new Vector2(28.7399998F, -3.32299995F), new Vector2(28.4239998F, -13.448F), new Vector2(21.7789993F, -19.1429996F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    builder.BeginFigure(new Vector2(20.4080009F, 0.474999994F));
                    builder.AddLine(new Vector2(0.0529999994F, 21.5680008F));
                    builder.AddLine(new Vector2(-20.4080009F, 0.474999994F));
                    builder.AddCubicBezier(new Vector2(-24.4160004F, -3.74399996F), new Vector2(-25.2600002F, -11.6540003F), new Vector2(-19.5650005F, -16.5049992F));
                    builder.AddCubicBezier(new Vector2(-13.7639999F, -21.4619999F), new Vector2(-7.01399994F, -17.8780003F), new Vector2(-4.4829998F, -15.3459997F));
                    builder.AddLine(new Vector2(0.0529999994F, -10.7060003F));
                    builder.AddLine(new Vector2(4.48199987F, -15.3459997F));
                    builder.AddCubicBezier(new Vector2(6.90799999F, -17.8780003F), new Vector2(13.7629995F, -21.4619999F), new Vector2(19.5639992F, -16.5049992F));
                    builder.AddCubicBezier(new Vector2(25.2600002F, -11.6540003F), new Vector2(24.4160004F, -3.74399996F), new Vector2(20.4080009F, 0.474999994F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Group 1 Offset:<63, 62.263>
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2.05699992F, -17.6650009F));
                    builder.AddCubicBezier(new Vector2(7.43599987F, -23.2549992F), new Vector2(15.9790001F, -23.9939995F), new Vector2(21.7800007F, -19.1429996F));
                    builder.AddCubicBezier(new Vector2(28.4239998F, -13.4469995F), new Vector2(28.7409992F, -3.32200003F), new Vector2(22.8339996F, 2.79399991F));
                    builder.AddLine(new Vector2(2.37199998F, 23.8889999F));
                    builder.AddCubicBezier(new Vector2(1.74000001F, 24.5219994F), new Vector2(0.896000028F, 24.8369999F), new Vector2(-0.0529999994F, 24.8369999F));
                    builder.AddCubicBezier(new Vector2(-0.897000015F, 24.8369999F), new Vector2(-1.74100006F, 24.5219994F), new Vector2(-2.37400007F, 23.8889999F));
                    builder.AddLine(new Vector2(-22.8349991F, 2.79399991F));
                    builder.AddCubicBezier(new Vector2(-28.7409992F, -3.32200003F), new Vector2(-28.4230003F, -13.4469995F), new Vector2(-21.7789993F, -19.1429996F));
                    builder.AddCubicBezier(new Vector2(-15.0290003F, -24.8379993F), new Vector2(-6.38199997F, -22.0949993F), new Vector2(-2.05699992F, -17.6650009F));
                    builder.AddLine(new Vector2(0.0529999994F, -15.5570002F));
                    builder.AddLine(new Vector2(2.05699992F, -17.6650009F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 1 Offset:<63, 62.263>
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostBlack_FF211B1C_to_TransparentAlmostBlack_00211B1C()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0x21, 0x1B, 0x1C), StepThenHoldEasingFunction());
                // AlmostBlack_FF211B1C
                result.InsertKeyFrame(0.0666666701F, Color.FromArgb(0xFF, 0x21, 0x1B, 0x1C), HoldThenStepEasingFunction());
                // TransparentAlmostBlack_00211B1C
                result.InsertKeyFrame(0.116666667F, Color.FromArgb(0x00, 0x21, 0x1B, 0x1C), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Group 1 Offset:<63, 62.263>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_AlmostCrimson_FFDB3939()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.116666667F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // AlmostCrimson_FFDB3939
                result.InsertKeyFrame(0.25F, Color.FromArgb(0xFF, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_0()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.266666681F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_99DB3939
                result.InsertKeyFrame(0.633333325F, Color.FromArgb(0x99, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.800000012F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_1()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.233333334F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_99DB3939
                result.InsertKeyFrame(0.600000024F, Color.FromArgb(0x99, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.766666651F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_2()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.183333337F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_99DB3939
                result.InsertKeyFrame(0.550000012F, Color.FromArgb(0x99, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.716666639F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_3()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.150000006F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_99DB3939
                result.InsertKeyFrame(0.516666651F, Color.FromArgb(0x99, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.683333337F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_4()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.200000003F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_CCDB3939
                result.InsertKeyFrame(0.516666651F, Color.FromArgb(0xCC, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.783333361F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_5()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.166666672F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_CCDB3939
                result.InsertKeyFrame(0.483333319F, Color.FromArgb(0xCC, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.75F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_6()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.13333334F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_CCDB3939
                result.InsertKeyFrame(0.449999988F, Color.FromArgb(0xCC, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.716666639F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_7()
            {
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _stepThenHoldEasingFunction);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.100000001F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _holdThenStepEasingFunction);
                // SemiTransparentAlmostCrimson_CCDB3939
                result.InsertKeyFrame(0.416666657F, Color.FromArgb(0xCC, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                // TransparentAlmostCrimson_00DB3939
                result.InsertKeyFrame(0.683333337F, Color.FromArgb(0x00, 0xDB, 0x39, 0x39), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1 Offset:<63, 62.263>
            CompositionColorBrush AnimatedColorBrush_AlmostBlack_FF211B1C_to_TransparentAlmostBlack_00211B1C()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_AlmostBlack_FF211B1C_to_TransparentAlmostBlack_00211B1C(), RootProgress());
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1 Offset:<63, 62.263>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_AlmostCrimson_FFDB3939()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_AlmostCrimson_FFDB3939(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_0()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_0(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_1()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_1(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_2()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_2(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_3()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_3(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_4()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_4(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_5()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_5(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_6()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_6(), _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_7()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_7(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(63F, 63F);
                // ShapeGroup: Group 1 Offset:<63, 62.263>
                result.Shapes.Add(SpriteShape_0());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_0(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_1()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(63F, 63F);
                // ShapeGroup: Group 1 Offset:<63, 62.263>
                result.Shapes.Add(SpriteShape_1());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_1(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_2()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, -34.25F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_2());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_2(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_0(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_3()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-0.25F, -33.75F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_3());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_3(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_1(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_4()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, -34F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_4());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_4(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_2(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_5()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-0.25F, -34F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_5());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_5(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_3(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_6()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, -34.25F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_6());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_6(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_4(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_7()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-0.25F, -34.25F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_7());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_7(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_5(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_8()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-0.25F, -33.75F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_8());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_8(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_6(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_9()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-0.25F, -34.75F);
                // ShapeGroup: Ellipse 1 Offset:<-0.235, -34.489>
                result.Shapes.Add(SpriteShape_9());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_9(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_7(), _rootProgress);
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_5p077()
            {
                var result = _ellipse_5p077 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(5.07649994F, 5.07649994F);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1 Offset:<63, 62.263>
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1 Offset:<63, 62.263>
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Group 1 Offset:<63, 62.263>
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<63, 62.263>
                var result = CreateSpriteShape(PathGeometry_0(), new Matrix3x2(1F, 0F, 0F, 1F, 63F, 62.2630005F), AnimatedColorBrush_AlmostBlack_FF211B1C_to_TransparentAlmostBlack_00211B1C());
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<63, 62.263>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 63F, 62.2630005F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_AlmostCrimson_FFDB3939());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(Ellipse_5p077(), new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_0());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_1());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_2());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_3());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_6()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_4());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_7()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_5());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_8()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_6());
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_9()
            {
                // Offset:<-0.235, -34.489>
                var result = CreateSpriteShape(_ellipse_5p077, new Matrix3x2(1F, 0F, 0F, 1F, -0.234999999F, -34.4889984F), AnimatedColorBrush_TransparentAlmostCrimson_00DB3939_to_TransparentAlmostCrimson_00DB3939_7());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                propertySet.InsertScalar("t0", 0F);
                propertySet.InsertScalar("t1", 0F);
                propertySet.InsertScalar("t2", 0F);
                propertySet.InsertScalar("t3", 0F);
                propertySet.InsertScalar("t4", 0F);
                propertySet.InsertScalar("t5", 0F);
                propertySet.InsertScalar("t6", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                StartProgressBoundAnimation(propertySet, "t0", t0ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(propertySet, "t1", t1ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(propertySet, "t2", t2ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(propertySet, "t3", t3ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(propertySet, "t4", t4ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(propertySet, "t5", t5ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(propertySet, "t6", t6ScalarAnimation_0_to_1(), _rootProgress);
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.186000004F, 1F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.26666671F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.633333266F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            ScalarKeyFrameAnimation t1ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.233333349F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.599999964F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.187000006F, 1F)));
                return result;
            }

            ScalarKeyFrameAnimation t2ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.183333352F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.549999952F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.187999994F, 1F)));
                return result;
            }

            ScalarKeyFrameAnimation t3ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.150000021F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.516666591F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.182999998F, 1F)));
                return result;
            }

            ScalarKeyFrameAnimation t4ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.200000018F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.516666591F, 1F, _cubicBezierEasingFunction_1);
                return result;
            }

            ScalarKeyFrameAnimation t5ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.166666687F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.48333329F, 1F, _cubicBezierEasingFunction_1);
                return result;
            }

            ScalarKeyFrameAnimation t6ScalarAnimation_0_to_1()
            {
                var result = CreateScalarKeyFrameAnimation(0.133333355F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.449999958F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.244000003F, 1F)));
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(126F, 126F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                shapes.Add(ContainerShape_2());
                shapes.Add(ContainerShape_3());
                shapes.Add(ContainerShape_4());
                shapes.Add(ContainerShape_5());
                shapes.Add(ContainerShape_6());
                shapes.Add(ContainerShape_7());
                shapes.Add(ContainerShape_8());
                shapes.Add(ContainerShape_9());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(63.5F, 95.5F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.266666681F, new Vector2(63.5F, 95.5F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.633333266F, "(Pow(1-_.t0,3)*Vector2(63.5,95.5))+(3*Square(1-_.t0)*_.t0*Vector2(58.125,89.667))+(3*(1-_.t0)*Square(_.t0)*Vector2(35.875,65.333))+(Pow(_.t0,3)*Vector2(31.25,60.5))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.633333325F, new Vector2(31.25F, 60.5F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(62.75F, 95.75F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.233333334F, new Vector2(62.75F, 95.75F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.599999964F, "(Pow(1-_.t1,3)*Vector2(62.75,95.75))+(3*Square(1-_.t1)*_.t1*Vector2(57.542,100.667))+(3*(1-_.t1)*Square(_.t1)*Vector2(36.375,120.917))+(Pow(_.t1,3)*Vector2(31.5,125.25))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.600000024F, new Vector2(31.5F, 125.25F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(63F, 96.25F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.183333337F, new Vector2(63F, 96.25F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.549999952F, "(Pow(1-_.t2,3)*Vector2(63,96.25))+(3*Square(1-_.t2)*_.t2*Vector2(68.833,101.5))+(3*(1-_.t2)*Square(_.t2)*Vector2(93.083,123.5))+(Pow(_.t2,3)*Vector2(98,127.75))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.550000012F, new Vector2(98F, 127.75F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(63.25F, 95.5F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.150000006F, new Vector2(63.25F, 95.5F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.516666591F, "(Pow(1-_.t3,3)*Vector2(63.25,95.5))+(3*Square(1-_.t3)*_.t3*Vector2(68.833,89.375))+(3*(1-_.t3)*Square(_.t3)*Vector2(92.083,63.625))+(Pow(_.t3,3)*Vector2(96.75,58.75))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.516666651F, new Vector2(96.75F, 58.75F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(63.5F, 95.5F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.200000003F, new Vector2(63.5F, 95.5F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.516666591F, "(Pow(1-_.t4,3)*Vector2(63.5,95.5))+(3*Square(1-_.t4)*_.t4*Vector2(56.708,95.25))+(3*(1-_.t4)*Square(_.t4)*Vector2(29.542,94.25))+(Pow(_.t4,3)*Vector2(22.75,94))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.516666651F, new Vector2(22.75F, 94F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_5()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(62.75F, 95.75F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.166666672F, new Vector2(62.75F, 95.75F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.48333329F, "(Pow(1-_.t5,3)*Vector2(62.75,95.75))+(3*Square(1-_.t5)*_.t5*Vector2(62.792,102.292))+(3*(1-_.t5)*Square(_.t5)*Vector2(62.958,128.458))+(Pow(_.t5,3)*Vector2(63,135))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.483333319F, new Vector2(63F, 135F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_6()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(63F, 95.75F), _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                result.InsertKeyFrame(0.13333334F, new Vector2(63F, 95.75F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.449999958F, "(Pow(1-_.t6,3)*Vector2(63,95.75))+(3*Square(1-_.t6)*_.t6*Vector2(70.25,95.542))+(3*(1-_.t6)*Square(_.t6)*Vector2(99.25,94.708))+(Pow(_.t6,3)*Vector2(106.5,94.5))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.449999988F, new Vector2(106.5F, 94.5F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_7()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(62.75F, 95.25F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.100000001F, new Vector2(62.75F, 95.25F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.416666657F, new Vector2(62.75F, 56.75F), _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.172999993F, 1F)));
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0666666701F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.116666667F, new Vector2(0.800000012F, 0.800000012F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.850000024F, 0.850000024F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.116666667F, new Vector2(0.850000024F, 0.850000024F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.183333337F, new Vector2(0.899999976F, 0.899999976F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.25F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.266666681F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.633333325F, new Vector2(0.600000024F, 0.600000024F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.233333334F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.600000024F, new Vector2(0.600000024F, 0.600000024F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.183333337F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.550000012F, new Vector2(0.600000024F, 0.600000024F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_5()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.150000006F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.516666651F, new Vector2(0.600000024F, 0.600000024F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_6()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.200000003F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_7()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.166666672F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_8()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.13333334F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_9()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1.37F, 1.37F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.100000001F, new Vector2(1F, 1F), _cubicBezierEasingFunction_0);
                return result;
            }

            internal AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(126F, 126F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
