//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           6.1.0-build.109+gebc2a6a0a3
//       
//       Command:
//           LottieGen -MinimumUapVersion 11 -Namespace WindowsInternal.ComposableShell.Experiences -Interface ILottieVisual -Language CSharp -InputFile QA_Cellular.json
//       
//       Input file:
//           QA_Cellular.json (6596 bytes created 10:10-07:00 Mar 30 2020)
//       
//       Invoked on:
//           SIM10FRESH @ 17:59-07:00 Apr 1 2020
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    59 |
// |--------------------------+-------|
// | Animators                |    11 |
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     2 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     5 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace WindowsInternal.ComposableShell.Experiences
{
    // Name:        QA_Cellular
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    // ____________________________________________
    // | Theme property | Type  |  Default value  |
    // |________________|_______|_________________|
    // | Foreground     | Color | #FF000000 Black |
    // --------------------------------------------
    sealed class QA_Cellular : ILottieVisualSource
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Theme property: Foreground.
        internal static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);

        CompositionPropertySet _themeProperties;
        Color _themeForeground = c_themeForeground;

        // Theme properties.
        public Color Foreground
        {
            get => _themeForeground;
            set
            {
                _themeForeground = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)_themeForeground));
                }
            }
        }

        public CompositionPropertySet GetThemeProperties(Compositor compositor)
        {
            return EnsureThemeProperties(compositor);
        }

        internal static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties is null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)Foreground));
            }
            return _themeProperties;
        }

        public ILottieVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            if (AnimatedVisual.IsRuntimeCompatible())
            {
                return
                    new AnimatedVisual(
                        compositor,
                        _themeProperties
                        );
            }

            return null;
        }

        sealed class AnimatedVisual : ILottieVisual
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            CompositionColorBrush _themeColor_Foreground;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            // - - - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55499983F, 5.55499983F));
                    builder.AddLine(new Vector2(-5.55499983F, 5.55499983F));
                    builder.AddLine(new Vector2(-5.55499983F, -5.55499983F));
                    builder.AddLine(new Vector2(5.55499983F, -5.55499983F));
                    builder.AddLine(new Vector2(5.55499983F, 5.55499983F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55499983F, 11.1110001F));
                    builder.AddLine(new Vector2(-5.55499983F, 11.1110001F));
                    builder.AddLine(new Vector2(-5.55499983F, -11.1110001F));
                    builder.AddLine(new Vector2(5.55499983F, -11.1110001F));
                    builder.AddLine(new Vector2(5.55499983F, 11.1110001F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55499983F, 16.6660004F));
                    builder.AddLine(new Vector2(-5.55499983F, 16.6660004F));
                    builder.AddLine(new Vector2(-5.55499983F, -16.6660004F));
                    builder.AddLine(new Vector2(5.55499983F, -16.6660004F));
                    builder.AddLine(new Vector2(5.55499983F, 16.6660004F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55499983F, 22.2220001F));
                    builder.AddLine(new Vector2(-5.55499983F, 22.2220001F));
                    builder.AddLine(new Vector2(-5.55499983F, -22.2220001F));
                    builder.AddLine(new Vector2(5.55499983F, -22.2220001F));
                    builder.AddLine(new Vector2(5.55499983F, 22.2220001F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.55499983F, 27.7770004F));
                    builder.AddLine(new Vector2(-5.55499983F, 27.7770004F));
                    builder.AddLine(new Vector2(-5.55499983F, -27.7770004F));
                    builder.AddLine(new Vector2(5.55499983F, -27.7770004F));
                    builder.AddLine(new Vector2(5.55499983F, 27.7770004F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground()
            {
                var result = _themeColor_Foreground = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Foreground.W*1,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_3()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_4()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape(PathGeometry_0());
                result.CenterPoint = new Vector2(0F, 5.55499983F);
                result.Offset = new Vector2(20.4459991F, 84.1159973F);
                result.FillBrush = ThemeColor_Foreground();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_0(), RootProgress());
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                var result = _c.CreateSpriteShape(PathGeometry_1());
                result.CenterPoint = new Vector2(0F, 11.1110001F);
                result.Offset = new Vector2(35.4459991F, 78.5599976F);
                result.FillBrush = _themeColor_Foreground;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_1(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                var result = _c.CreateSpriteShape(PathGeometry_2());
                result.CenterPoint = new Vector2(0F, 16.6660004F);
                result.Offset = new Vector2(50.4459991F, 73.0049973F);
                result.FillBrush = _themeColor_Foreground;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_2(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                var result = _c.CreateSpriteShape(PathGeometry_3());
                result.CenterPoint = new Vector2(0F, 22.2220001F);
                result.Offset = new Vector2(65.4459991F, 67.4489975F);
                result.FillBrush = _themeColor_Foreground;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_3(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.CenterPoint = new Vector2(0F, 27.7770004F);
                result.Offset = new Vector2(80.4449997F, 61.8939972F);
                result.FillBrush = _themeColor_Foreground;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_4(), _rootProgress);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(1F, 0F), new Vector2(0.833000004F, 1F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0F, 1F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(100F, 100F);
                // Offset:<-1, -2.25>, Scale:<0.18, 0.18>
                result.TransformMatrix = new Matrix4x4(0.180000007F, 0F, 0F, 0F, 0F, 0.180000007F, 0F, 0F, 0F, 0F, 0F, 0F, -1F, -2.25F, 0F, 1F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_0());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_1());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_2());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_3());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_4());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), StepThenHoldEasingFunction());
                result.InsertKeyFrame(0.0666666701F, new Vector2(0.899999976F, 0.899999976F), HoldThenStepEasingFunction());
                result.InsertKeyFrame(0.466666669F, new Vector2(0.899999976F, 0F), CubicBezierEasingFunction_0());
                result.InsertKeyFrame(0.966666639F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_1());
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0500000007F, new Vector2(0.899999976F, 0.899999976F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.433333337F, new Vector2(0.899999976F, 0F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.949999988F, new Vector2(0.899999976F, 0.899999976F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0333333351F, new Vector2(0.899999976F, 0.899999976F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.400000006F, new Vector2(0.899999976F, 0F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.933333337F, new Vector2(0.899999976F, 0.899999976F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0166666675F, new Vector2(0.899999976F, 0.899999976F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.366666675F, new Vector2(0.899999976F, 0F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.916666687F, new Vector2(0.899999976F, 0.899999976F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Cellular
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.333333343F, new Vector2(0.899999976F, 0F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.899999976F, new Vector2(0.899999976F, 0.899999976F), _cubicBezierEasingFunction_1);
                return result;
            }

            internal AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(16F, 16F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
