//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           6.1.0-build.109+gebc2a6a0a3
//       
//       Command:
//           LottieGen -MinimumUapVersion 11 -Namespace WindowsInternal.ComposableShell.Experiences -Interface ILottieVisual -Language CSharp -InputFile QA_MobileHotspot.json
//       
//       Input file:
//           QA_MobileHotspot.json (15515 bytes created 10:10-07:00 Mar 30 2020)
//       
//       Invoked on:
//           SIM10FRESH @ 17:59-07:00 Apr 1 2020
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   169 |
// |--------------------------+-------|
// | Animators                |    55 |
// | Animated brushes         |     3 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     4 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     5 |
// | CompositionSpriteShapes  |    10 |
// |--------------------------+-------|
// | Brushes                  |     3 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedIconPrototype
{
    // Name:        QA_MobileHotspot
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    // ____________________________________________
    // | Theme property | Type  |  Default value  |
    // |________________|_______|_________________|
    // | Foreground     | Color | #FF000000 Black |
    // --------------------------------------------
    sealed class QA_MobileHotspot : ILottieVisualSource
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Theme property: Foreground.
        internal static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);

        CompositionPropertySet _themeProperties;
        Color _themeForeground = c_themeForeground;

        // Theme properties.
        public Color Foreground
        {
            get => _themeForeground;
            set
            {
                _themeForeground = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)_themeForeground));
                }
            }
        }

        public CompositionPropertySet GetThemeProperties(Compositor compositor)
        {
            return EnsureThemeProperties(compositor);
        }

        internal static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties is null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)Foreground));
            }
            return _themeProperties;
        }

        public ILottieVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            if (AnimatedVisual.IsRuntimeCompatible())
            {
                return
                    new AnimatedVisual(
                        compositor,
                        _themeProperties
                        );
            }

            return null;
        }

        sealed class AnimatedVisual : ILottieVisual
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            CompositionColorBrush _themeColor_Foreground_0;
            CompositionColorBrush _themeColor_Foreground_1;
            CompositionColorBrush _themeColor_Foreground_2;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_3;
            CompositionPathGeometry _pathGeometry_4;
            CompositionPathGeometry _pathGeometry_5;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;
            Vector2KeyFrameAnimation _scaleVector2Animation_1;
            Vector2KeyFrameAnimation _scaleVector2Animation_2;
            Vector2KeyFrameAnimation _scaleVector2Animation_3;
            Vector2KeyFrameAnimation _scaleVector2Animation_4;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            void BindProperty2(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName0,
                CompositionObject referencedObject0,
                string referenceParameterName1,
                CompositionObject referencedObject1)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName0, referencedObject0);
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName1, referencedObject1);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - - - Layer: Layer 10
            // - - Path 1.PathGeometry
            // - Path
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-2.875F, -25.8770008F));
                    builder.AddCubicBezier(new Vector2(-2.875F, -25.8770008F), new Vector2(2.875F, -25.8770008F), new Vector2(2.875F, -25.8770008F));
                    builder.AddCubicBezier(new Vector2(2.875F, -25.8770008F), new Vector2(2.875F, 25.8770008F), new Vector2(2.875F, 25.8770008F));
                    builder.AddCubicBezier(new Vector2(2.875F, 25.8770008F), new Vector2(-2.875F, 25.8770008F), new Vector2(-2.875F, 25.8770008F));
                    builder.AddCubicBezier(new Vector2(-2.875F, 25.8770008F), new Vector2(-2.875F, -25.8770008F), new Vector2(-2.875F, -25.8770008F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - - - Layer: Layer 10
            // - - Path 1.PathGeometry
            // - Path
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-2.875F, -25.8770008F));
                    builder.AddCubicBezier(new Vector2(-2.875F, -25.8770008F), new Vector2(2.875F, -25.8770008F), new Vector2(2.875F, -25.8770008F));
                    builder.AddCubicBezier(new Vector2(2.875F, -25.8770008F), new Vector2(2.89499998F, -25.9190006F), new Vector2(2.89499998F, -25.9190006F));
                    builder.AddCubicBezier(new Vector2(2.89499998F, -25.9190006F), new Vector2(-2.85500002F, -25.9190006F), new Vector2(-2.85500002F, -25.9190006F));
                    builder.AddCubicBezier(new Vector2(-2.85500002F, -25.9190006F), new Vector2(-2.875F, -25.8770008F), new Vector2(-2.875F, -25.8770008F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - - - Layer: Layer 1
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-2.875F, -25.8770008F));
                    builder.AddLine(new Vector2(2.875F, -25.8770008F));
                    builder.AddLine(new Vector2(2.875F, 25.8770008F));
                    builder.AddLine(new Vector2(-2.875F, 25.8770008F));
                    builder.AddLine(new Vector2(-2.875F, -25.8770008F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-1.77400005F, -18.2840004F));
                    builder.AddCubicBezier(new Vector2(0.65200001F, -15.8579998F), new Vector2(2.52399993F, -13.0579996F), new Vector2(3.84100008F, -9.88300037F));
                    builder.AddCubicBezier(new Vector2(5.15899992F, -6.73799992F), new Vector2(5.81799984F, -3.44400001F), new Vector2(5.81799984F, 0F));
                    builder.AddCubicBezier(new Vector2(5.81799984F, 3.44400001F), new Vector2(5.15899992F, 6.75299978F), new Vector2(3.84100008F, 9.92800045F));
                    builder.AddCubicBezier(new Vector2(2.52399993F, 13.073F), new Vector2(0.65200001F, 15.8579998F), new Vector2(-1.77400005F, 18.2840004F));
                    builder.AddLine(new Vector2(-5.81799984F, 14.2410002F));
                    builder.AddCubicBezier(new Vector2(-3.93099999F, 12.3540001F), new Vector2(-2.49300003F, 10.1829996F), new Vector2(-1.505F, 7.72700024F));
                    builder.AddCubicBezier(new Vector2(-0.486999989F, 5.27099991F), new Vector2(0.023F, 2.69499993F), new Vector2(0.023F, 0F));
                    builder.AddCubicBezier(new Vector2(0.023F, -2.69499993F), new Vector2(-0.486999989F, -5.27099991F), new Vector2(-1.505F, -7.72700024F));
                    builder.AddCubicBezier(new Vector2(-2.49300003F, -10.1829996F), new Vector2(-3.93099999F, -12.3540001F), new Vector2(-5.81799984F, -14.2410002F));
                    builder.AddLine(new Vector2(-1.77400005F, -18.2840004F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.81799984F, -14.2410002F));
                    builder.AddCubicBezier(new Vector2(3.93099999F, -12.3540001F), new Vector2(2.47799993F, -10.1829996F), new Vector2(1.46000004F, -7.72700024F));
                    builder.AddCubicBezier(new Vector2(0.442000002F, -5.27099991F), new Vector2(-0.0670000017F, -2.69499993F), new Vector2(-0.0670000017F, 0F));
                    builder.AddCubicBezier(new Vector2(-0.0670000017F, 2.69499993F), new Vector2(0.442000002F, 5.27099991F), new Vector2(1.46000004F, 7.72700024F));
                    builder.AddCubicBezier(new Vector2(2.47799993F, 10.1829996F), new Vector2(3.93099999F, 12.3540001F), new Vector2(5.81799984F, 14.2410002F));
                    builder.AddLine(new Vector2(1.77499998F, 18.2840004F));
                    builder.AddCubicBezier(new Vector2(-0.651000023F, 15.8579998F), new Vector2(-2.523F, 13.073F), new Vector2(-3.84100008F, 9.92800045F));
                    builder.AddCubicBezier(new Vector2(-5.15899992F, 6.75299978F), new Vector2(-5.81799984F, 3.44400001F), new Vector2(-5.81799984F, 0F));
                    builder.AddCubicBezier(new Vector2(-5.81799984F, -3.44400001F), new Vector2(-5.15899992F, -6.73799992F), new Vector2(-3.84100008F, -9.88300037F));
                    builder.AddCubicBezier(new Vector2(-2.523F, -13.0579996F), new Vector2(-0.651000023F, -15.8579998F), new Vector2(1.77499998F, -18.2840004F));
                    builder.AddLine(new Vector2(5.81799984F, -14.2410002F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-4.26800013F, -30.5039997F));
                    builder.AddCubicBezier(new Vector2(-0.194999993F, -26.4009991F), new Vector2(2.92000008F, -21.743F), new Vector2(5.07600021F, -16.5319996F));
                    builder.AddCubicBezier(new Vector2(7.26200008F, -11.3210001F), new Vector2(8.35599995F, -5.80999994F), new Vector2(8.35599995F, 0F));
                    builder.AddCubicBezier(new Vector2(8.35599995F, 5.80999994F), new Vector2(7.26200008F, 11.3210001F), new Vector2(5.07600021F, 16.5319996F));
                    builder.AddCubicBezier(new Vector2(2.92000008F, 21.743F), new Vector2(-0.194999993F, 26.4009991F), new Vector2(-4.26800013F, 30.5039997F));
                    builder.AddLine(new Vector2(-8.35599995F, 26.4160004F));
                    builder.AddCubicBezier(new Vector2(-4.82200003F, 22.882F), new Vector2(-2.11199999F, 18.8530006F), new Vector2(-0.224999994F, 14.3310003F));
                    builder.AddCubicBezier(new Vector2(1.66199994F, 9.77900028F), new Vector2(2.60500002F, 5.00199986F), new Vector2(2.60500002F, 0F));
                    builder.AddCubicBezier(new Vector2(2.60500002F, -5.00199986F), new Vector2(1.66199994F, -9.76399994F), new Vector2(-0.224999994F, -14.2860003F));
                    builder.AddCubicBezier(new Vector2(-2.11199999F, -18.8379993F), new Vector2(-4.82200003F, -22.882F), new Vector2(-8.35599995F, -26.4160004F));
                    builder.AddLine(new Vector2(-4.26800013F, -30.5039997F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(8.35599995F, -26.4160004F));
                    builder.AddCubicBezier(new Vector2(4.82200003F, -22.882F), new Vector2(2.11199999F, -18.8379993F), new Vector2(0.224999994F, -14.2860003F));
                    builder.AddCubicBezier(new Vector2(-1.66199994F, -9.76399994F), new Vector2(-2.60599995F, -5.00199986F), new Vector2(-2.60599995F, 0F));
                    builder.AddCubicBezier(new Vector2(-2.60599995F, 5.00199986F), new Vector2(-1.66199994F, 9.77900028F), new Vector2(0.224999994F, 14.3310003F));
                    builder.AddCubicBezier(new Vector2(2.11199999F, 18.8530006F), new Vector2(4.82200003F, 22.882F), new Vector2(8.35599995F, 26.4160004F));
                    builder.AddLine(new Vector2(4.26800013F, 30.5039997F));
                    builder.AddCubicBezier(new Vector2(0.194999993F, 26.4009991F), new Vector2(-2.93499994F, 21.743F), new Vector2(-5.12099981F, 16.5319996F));
                    builder.AddCubicBezier(new Vector2(-7.27699995F, 11.3210001F), new Vector2(-8.35599995F, 5.80999994F), new Vector2(-8.35599995F, 0F));
                    builder.AddCubicBezier(new Vector2(-8.35599995F, -5.80999994F), new Vector2(-7.27699995F, -11.3210001F), new Vector2(-5.12099981F, -16.5319996F));
                    builder.AddCubicBezier(new Vector2(-2.93499994F, -21.743F), new Vector2(0.194999993F, -26.4009991F), new Vector2(4.26800013F, -30.5039997F));
                    builder.AddLine(new Vector2(8.35599995F, -26.4160004F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_0()
            {
                var result = _themeColor_Foreground_0 = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Foreground.W*1,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_1()
            {
                var result = _themeColor_Foreground_1 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_1_to_0_0(), _rootProgress);
                return result;
            }

            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_2()
            {
                var result = _themeColor_Foreground_2 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_1_to_0_1(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 1
            CompositionContainerShape ContainerShape_0()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_01());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_1(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 2
            CompositionContainerShape ContainerShape_1()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_02());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_03());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_2(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 4
            CompositionContainerShape ContainerShape_2()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_04());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_05());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_3(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 6
            CompositionContainerShape ContainerShape_3()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_06());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_07());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_4(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 8
            CompositionContainerShape ContainerShape_4()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_08());
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_09());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_5(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 10
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_0(), RootProgress());
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 1
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_3()
            {
                var result = _pathGeometry_3 = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_4()
            {
                var result = _pathGeometry_4 = _c.CreatePathGeometry(new CompositionPath(Geometry_5()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_5()
            {
                var result = _pathGeometry_5 = _c.CreatePathGeometry(new CompositionPath(Geometry_6()));
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<50, 61.463>
                var result = CreateSpriteShape(PathGeometry_0(), new Matrix3x2(1F, 0F, 0F, 1F, 50F, 61.4630013F), ThemeColor_Foreground_0());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_0(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 1
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape(PathGeometry_1());
                result.CenterPoint = new Vector2(0F, 25.8770008F);
                result.Offset = new Vector2(50F, 61.1679993F);
                result.FillBrush = _themeColor_Foreground_0;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_0(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 2
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape(PathGeometry_2());
                result.FillBrush = ThemeColor_Foreground_1();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_1(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_0(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 2
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape(PathGeometry_3());
                result.FillBrush = _themeColor_Foreground_1;
                StartProgressBoundAnimation(result, "Scale", _scaleVector2Animation_1, _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_1(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 4
            // Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.FillBrush = ThemeColor_Foreground_2();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_2(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_2(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 4
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape(PathGeometry_5());
                result.FillBrush = _themeColor_Foreground_2;
                StartProgressBoundAnimation(result, "Scale", _scaleVector2Animation_2, _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_3(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 6
            // Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_2);
                result.FillBrush = _themeColor_Foreground_0;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_3(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_4(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 6
            // Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_3);
                result.FillBrush = _themeColor_Foreground_0;
                StartProgressBoundAnimation(result, "Scale", _scaleVector2Animation_3, _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_5(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 8
            // Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_4);
                result.FillBrush = _themeColor_Foreground_0;
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_4(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_6(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 8
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_5);
                result.FillBrush = _themeColor_Foreground_0;
                StartProgressBoundAnimation(result, "Scale", _scaleVector2Animation_4, _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_7(), _rootProgress);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(1F, 0F), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0F, 1F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 10
            // Path 1.PathGeometry
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                var result = CreatePathKeyFrameAnimation(0F, new CompositionPath(Geometry_0()), HoldThenStepEasingFunction());
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_1()), CubicBezierEasingFunction_0());
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_0_0()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.333333343F, 1F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.5F, 0F, CubicBezierEasingFunction_1());
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_0_1()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.333333343F, 1F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.416666657F, 0F, _cubicBezierEasingFunction_1);
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(100F, 100F);
                // Scale:<0.16, 0.16>
                result.TransformMatrix = new Matrix4x4(0.159999996F, 0F, 0F, 0F, 0F, 0.159999996F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                var shapes = result.Shapes;
                // Layer: Layer 10
                shapes.Add(SpriteShape_00());
                // Layer: Layer 1
                shapes.Add(ContainerShape_0());
                // Layer: Layer 2
                shapes.Add(ContainerShape_1());
                // Layer: Layer 4
                shapes.Add(ContainerShape_2());
                // Layer: Layer 6
                shapes.Add(ContainerShape_3());
                // Layer: Layer 8
                shapes.Add(ContainerShape_4());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 2
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(69.0559998F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0833333358F, new Vector2(69.0559998F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(74.0559998F, 45.3240013F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 2
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(30.9440002F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0833333358F, new Vector2(30.9440002F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(25.9440002F, 45.3240013F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 4
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(83.0329971F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0833333358F, new Vector2(83.0329971F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.416666657F, new Vector2(90.5329971F, 45.3240013F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 4
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(16.9669991F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0833333358F, new Vector2(16.9669991F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.416666657F, new Vector2(8.71700001F, 45.3240013F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 6
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(49.0559998F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.550000012F, new Vector2(49.0559998F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.983333349F, new Vector2(69.0559998F, 45.3240013F), _cubicBezierEasingFunction_2);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 6
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_5()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(49.4440002F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.550000012F, new Vector2(49.4440002F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.983333349F, new Vector2(30.9440002F, 45.3240013F), _cubicBezierEasingFunction_2);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 8
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_6()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(49.7830009F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(49.7830009F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.833333313F, new Vector2(83.0329971F, 45.3240013F), _cubicBezierEasingFunction_2);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 8
            // ShapeGroup: Group 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_7()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(49.4669991F, 45.3240013F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(49.4669991F, 45.3240013F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.833333313F, new Vector2(16.9669991F, 45.3240013F), _cubicBezierEasingFunction_2);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // - Layer: Layer 1
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 0F), StepThenHoldEasingFunction());
                result.InsertKeyFrame(0.416666657F, new Vector2(1F, 0F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.983333349F, new Vector2(1F, 1F), _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0F, 1F)));
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                var result = _scaleVector2Animation_1 = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0833333358F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(1.10000002F, 1.10000002F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_2()
            {
                var result = _scaleVector2Animation_2 = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0833333358F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.416666657F, new Vector2(1.10000002F, 1.10000002F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_3()
            {
                var result = _scaleVector2Animation_3 = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.550000012F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.983333349F, new Vector2(1F, 1F), CubicBezierEasingFunction_2());
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_4()
            {
                var result = _scaleVector2Animation_4 = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.833333313F, new Vector2(1F, 1F), _cubicBezierEasingFunction_2);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 10
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0.5F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0.416666657F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0.516666651F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 4
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0.433333337F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 6
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0.550000012F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - New - Mobile Hotspot
            // Layer: Layer 8
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_5()
            {
                var result = CreateVector2KeyFrameAnimation(0.5F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            internal AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(16F, 16F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
