//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           6.1.0-build.109+gebc2a6a0a3
//       
//       Command:
//           LottieGen -MinimumUapVersion 11 -Namespace WindowsInternal.ComposableShell.Experiences -Interface ILottieVisual -Language CSharp -InputFile QA_Wifi.json
//       
//       Input file:
//           QA_Wifi.json (12495 bytes created 10:10-07:00 Mar 30 2020)
//       
//       Invoked on:
//           SIM10FRESH @ 17:59-07:00 Apr 1 2020
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   159 |
// |--------------------------+-------|
// | Animators                |    45 |
// | Animated brushes         |     7 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     8 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     6 |
// | CompositionSpriteShapes  |     7 |
// |--------------------------+-------|
// | Brushes                  |     7 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace WindowsInternal.ComposableShell.Experiences
{
    // Name:        QA_Wifi
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    // ____________________________________________
    // | Theme property | Type  |  Default value  |
    // |________________|_______|_________________|
    // | Foreground     | Color | #FF000000 Black |
    // --------------------------------------------
    sealed class QA_Wifi : ILottieVisualSource
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Theme property: Foreground.
        internal static readonly Color c_themeForeground = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);

        CompositionPropertySet _themeProperties;
        Color _themeForeground = c_themeForeground;

        // Theme properties.
        public Color Foreground
        {
            get => _themeForeground;
            set
            {
                _themeForeground = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)_themeForeground));
                }
            }
        }

        public CompositionPropertySet GetThemeProperties(Compositor compositor)
        {
            return EnsureThemeProperties(compositor);
        }

        internal static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties is null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Foreground", ColorAsVector4((Color)Foreground));
            }
            return _themeProperties;
        }

        public ILottieVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            if (AnimatedVisual.IsRuntimeCompatible())
            {
                return
                    new AnimatedVisual(
                        compositor,
                        _themeProperties
                        );
            }

            return null;
        }

        sealed class AnimatedVisual : ILottieVisual
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            CompositionColorBrush _themeColor_Foreground_1;
            CompositionColorBrush _themeColor_Foreground_2;
            CompositionColorBrush _themeColor_Foreground_3;
            CompositionColorBrush _themeColor_Foreground_4;
            CompositionColorBrush _themeColor_Foreground_5;
            CompositionColorBrush _themeColor_Foreground_6;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_3;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            void BindProperty2(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName0,
                CompositionObject referencedObject0,
                string referenceParameterName1,
                CompositionObject referencedObject1)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName0, referencedObject0);
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName1, referencedObject1);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            // - - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - - ShapeGroup: Group 1
            // - Path 1.PathGeometry
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, -10F));
                    builder.AddCubicBezier(new Vector2(1.38900006F, -10F), new Vector2(2.69099998F, -9.73999977F), new Vector2(3.9059999F, -9.21899986F));
                    builder.AddCubicBezier(new Vector2(5.12099981F, -8.69799995F), new Vector2(6.17999983F, -7.98600006F), new Vector2(7.08300018F, -7.08300018F));
                    builder.AddCubicBezier(new Vector2(7.98600006F, -6.17999983F), new Vector2(8.69799995F, -5.12099981F), new Vector2(9.21899986F, -3.9059999F));
                    builder.AddCubicBezier(new Vector2(9.73999977F, -2.69099998F), new Vector2(10F, -1.38900006F), new Vector2(10F, 0F));
                    builder.AddCubicBezier(new Vector2(10F, 1.38900006F), new Vector2(9.73999977F, 2.69099998F), new Vector2(9.21899986F, 3.9059999F));
                    builder.AddCubicBezier(new Vector2(8.69799995F, 5.12099981F), new Vector2(7.98600006F, 6.17999983F), new Vector2(7.08300018F, 7.08300018F));
                    builder.AddCubicBezier(new Vector2(6.17999983F, 7.98600006F), new Vector2(5.12099981F, 8.69799995F), new Vector2(3.9059999F, 9.21899986F));
                    builder.AddCubicBezier(new Vector2(2.69099998F, 9.73999977F), new Vector2(1.38900006F, 10F), new Vector2(0F, 10F));
                    builder.AddCubicBezier(new Vector2(-1.38900006F, 10F), new Vector2(-2.69099998F, 9.73999977F), new Vector2(-3.9059999F, 9.21899986F));
                    builder.AddCubicBezier(new Vector2(-5.12099981F, 8.69799995F), new Vector2(-6.17999983F, 7.98600006F), new Vector2(-7.08300018F, 7.08300018F));
                    builder.AddCubicBezier(new Vector2(-7.98600006F, 6.17999983F), new Vector2(-8.69799995F, 5.12099981F), new Vector2(-9.21899986F, 3.9059999F));
                    builder.AddCubicBezier(new Vector2(-9.73999977F, 2.69099998F), new Vector2(-10F, 1.38900006F), new Vector2(-10F, 0F));
                    builder.AddCubicBezier(new Vector2(-10F, -1.38900006F), new Vector2(-9.73999977F, -2.69099998F), new Vector2(-9.21899986F, -3.9059999F));
                    builder.AddCubicBezier(new Vector2(-8.69799995F, -5.12099981F), new Vector2(-7.98600006F, -6.17999983F), new Vector2(-7.08300018F, -7.08300018F));
                    builder.AddCubicBezier(new Vector2(-6.17999983F, -7.98600006F), new Vector2(-5.12099981F, -8.69799995F), new Vector2(-3.9059999F, -9.21899986F));
                    builder.AddCubicBezier(new Vector2(-2.69099998F, -9.73999977F), new Vector2(-1.38900006F, -10F), new Vector2(0F, -10F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-20F, 20F));
                    builder.AddCubicBezier(new Vector2(-20F, 16.3190002F), new Vector2(-19.5319996F, 12.7779999F), new Vector2(-18.5939999F, 9.375F));
                    builder.AddCubicBezier(new Vector2(-17.6560001F, 5.97200012F), new Vector2(-16.302F, 2.79500008F), new Vector2(-14.5310001F, -0.156000003F));
                    builder.AddCubicBezier(new Vector2(-12.7600002F, -3.10700011F), new Vector2(-10.677F, -5.81599998F), new Vector2(-8.28100014F, -8.28100014F));
                    builder.AddCubicBezier(new Vector2(-5.88500023F, -10.7460003F), new Vector2(-3.19400001F, -12.8299999F), new Vector2(-0.208000004F, -14.5310001F));
                    builder.AddCubicBezier(new Vector2(2.77800012F, -16.2320004F), new Vector2(5.97200012F, -17.5699997F), new Vector2(9.375F, -18.5419998F));
                    builder.AddCubicBezier(new Vector2(12.7779999F, -19.5139999F), new Vector2(16.3190002F, -20F), new Vector2(20F, -20F));
                    builder.AddLine(new Vector2(20F, -13.3330002F));
                    builder.AddCubicBezier(new Vector2(16.9440002F, -13.3330002F), new Vector2(13.993F, -12.934F), new Vector2(11.1459999F, -12.1350002F));
                    builder.AddCubicBezier(new Vector2(8.29899979F, -11.3360004F), new Vector2(5.6420002F, -10.2259998F), new Vector2(3.17700005F, -8.80200005F));
                    builder.AddCubicBezier(new Vector2(0.712000012F, -7.37799978F), new Vector2(-1.528F, -5.64300013F), new Vector2(-3.54200006F, -3.5940001F));
                    builder.AddCubicBezier(new Vector2(-5.55600023F, -1.54499996F), new Vector2(-7.29199982F, 0.712000012F), new Vector2(-8.75F, 3.17700005F));
                    builder.AddCubicBezier(new Vector2(-10.2080002F, 5.6420002F), new Vector2(-11.3360004F, 8.29899979F), new Vector2(-12.1350002F, 11.1459999F));
                    builder.AddCubicBezier(new Vector2(-12.934F, 13.993F), new Vector2(-13.3330002F, 16.9440002F), new Vector2(-13.3330002F, 20F));
                    builder.AddLine(new Vector2(-20F, 20F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-30F, 30F));
                    builder.AddCubicBezier(new Vector2(-30F, 24.4790001F), new Vector2(-29.2889996F, 19.1660004F), new Vector2(-27.8649998F, 14.0620003F));
                    builder.AddCubicBezier(new Vector2(-26.441F, 8.95800018F), new Vector2(-24.427F, 4.16699982F), new Vector2(-21.823F, -0.312000006F));
                    builder.AddCubicBezier(new Vector2(-19.2189999F, -4.79099989F), new Vector2(-16.0939999F, -8.83699989F), new Vector2(-12.448F, -12.448F));
                    builder.AddCubicBezier(new Vector2(-8.80200005F, -16.059F), new Vector2(-4.75600004F, -19.184F), new Vector2(-0.312000006F, -21.823F));
                    builder.AddCubicBezier(new Vector2(4.13199997F, -24.4619999F), new Vector2(8.90600014F, -26.4759998F), new Vector2(14.0100002F, -27.8649998F));
                    builder.AddCubicBezier(new Vector2(19.1140003F, -29.2539997F), new Vector2(24.4440002F, -29.9650002F), new Vector2(30F, -30F));
                    builder.AddLine(new Vector2(30F, -23.3330002F));
                    builder.AddCubicBezier(new Vector2(25.1040001F, -23.3330002F), new Vector2(20.3990002F, -22.7080002F), new Vector2(15.8850002F, -21.4580002F));
                    builder.AddCubicBezier(new Vector2(11.3710003F, -20.2080002F), new Vector2(7.11800003F, -18.4029999F), new Vector2(3.125F, -16.0419998F));
                    builder.AddCubicBezier(new Vector2(-0.867999971F, -13.6809998F), new Vector2(-4.46199989F, -10.9020004F), new Vector2(-7.65600014F, -7.70800018F));
                    builder.AddCubicBezier(new Vector2(-10.8500004F, -4.51399994F), new Vector2(-13.6459999F, -0.902999997F), new Vector2(-16.0419998F, 3.125F));
                    builder.AddCubicBezier(new Vector2(-18.4379997F, 7.15299988F), new Vector2(-20.2250004F, 11.3889999F), new Vector2(-21.4060001F, 15.8330002F));
                    builder.AddCubicBezier(new Vector2(-22.5869999F, 20.2770004F), new Vector2(-23.2290001F, 25F), new Vector2(-23.3330002F, 30F));
                    builder.AddLine(new Vector2(-30F, 30F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path 1.PathGeometry
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-40F, 40F));
                    builder.AddCubicBezier(new Vector2(-40F, 32.6389999F), new Vector2(-39.0449982F, 25.5559998F), new Vector2(-37.1349983F, 18.75F));
                    builder.AddCubicBezier(new Vector2(-35.2249985F, 11.9440002F), new Vector2(-32.5340004F, 5.57299995F), new Vector2(-29.0620003F, -0.36500001F));
                    builder.AddCubicBezier(new Vector2(-25.5900002F, -6.30299997F), new Vector2(-21.4230003F, -11.7010002F), new Vector2(-16.5620003F, -16.5620003F));
                    builder.AddCubicBezier(new Vector2(-11.7010002F, -21.4230003F), new Vector2(-6.30299997F, -25.5900002F), new Vector2(-0.36500001F, -29.0620003F));
                    builder.AddCubicBezier(new Vector2(5.57299995F, -32.5340004F), new Vector2(11.9440002F, -35.2249985F), new Vector2(18.75F, -37.1349983F));
                    builder.AddCubicBezier(new Vector2(25.5559998F, -39.0449982F), new Vector2(32.6389999F, -40F), new Vector2(40F, -40F));
                    builder.AddLine(new Vector2(40F, -33.3330002F));
                    builder.AddCubicBezier(new Vector2(33.2639999F, -33.3330002F), new Vector2(26.7880001F, -32.4650002F), new Vector2(20.573F, -30.7290001F));
                    builder.AddCubicBezier(new Vector2(14.3579998F, -28.993F), new Vector2(8.52400017F, -26.5270004F), new Vector2(3.07299995F, -23.3330002F));
                    builder.AddCubicBezier(new Vector2(-2.37800002F, -20.1389999F), new Vector2(-7.34399986F, -16.302F), new Vector2(-11.823F, -11.823F));
                    builder.AddCubicBezier(new Vector2(-16.302F, -7.34399986F), new Vector2(-20.1210003F, -2.39599991F), new Vector2(-23.2810001F, 3.02099991F));
                    builder.AddCubicBezier(new Vector2(-26.441F, 8.43799973F), new Vector2(-28.9060001F, 14.2709999F), new Vector2(-30.677F, 20.5209999F));
                    builder.AddCubicBezier(new Vector2(-32.4480019F, 26.7709999F), new Vector2(-33.3330002F, 33.2639999F), new Vector2(-33.3330002F, 40F));
                    builder.AddLine(new Vector2(-40F, 40F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_0()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Foreground.W*1,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 1
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_1()
            {
                var result = _themeColor_Foreground_1 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_1_to_0_0(), _rootProgress);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 2
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_2()
            {
                var result = _themeColor_Foreground_2 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_1_to_0_1(), _rootProgress);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 3
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_3()
            {
                var result = _themeColor_Foreground_3 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 1F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_1_to_0_2(), _rootProgress);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 11
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_4()
            {
                var result = _themeColor_Foreground_4 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_0_to_1_0(), _rootProgress);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 12
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_5()
            {
                var result = _themeColor_Foreground_5 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_0_to_1_1(), _rootProgress);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 13
            // ShapeGroup: Group 1
            // Color bound to theme property value: Foreground
            CompositionColorBrush ThemeColor_Foreground_6()
            {
                var result = _themeColor_Foreground_6 = _c.CreateColorBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                BindProperty2(result, "Color", "ColorRGB(_theme.Foreground.W*my.Opacity0,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", "_theme", _themeProperties, "my", propertySet);
                StartProgressBoundAnimation(propertySet, "Opacity0", Opacity0ScalarAnimation_0_to_1_2(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 1
            CompositionContainerShape ContainerShape_0()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_1());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_0(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 2
            CompositionContainerShape ContainerShape_1()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_2());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_1(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 3
            CompositionContainerShape ContainerShape_2()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_3());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_2(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 11
            CompositionContainerShape ContainerShape_3()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_4());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_3(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 12
            CompositionContainerShape ContainerShape_4()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_5());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_4(), _rootProgress);
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 13
            CompositionContainerShape ContainerShape_5()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                // ShapeGroup: Group 1
                result.Shapes.Add(SpriteShape_6());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_5(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // ShapeGroup: Group 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_3()
            {
                var result = _pathGeometry_3 = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
                return result;
            }

            // PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape(PathGeometry_0());
                result.Offset = new Vector2(81.2639999F, 79.2639999F);
                result.FillBrush = ThemeColor_Foreground_0();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_0(), RootProgress());
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 1
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                var result = _c.CreateSpriteShape(PathGeometry_1());
                result.CenterPoint = new Vector2(20F, 20F);
                result.Offset = new Vector2(71.2639999F, 69.2639999F);
                result.FillBrush = ThemeColor_Foreground_1();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_1(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 2
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                var result = _c.CreateSpriteShape(PathGeometry_2());
                result.CenterPoint = new Vector2(30F, 30F);
                result.Offset = new Vector2(61.2639999F, 59.2639999F);
                result.FillBrush = ThemeColor_Foreground_2();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_2(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 3
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                var result = _c.CreateSpriteShape(PathGeometry_3());
                result.CenterPoint = new Vector2(40F, 40F);
                result.Offset = new Vector2(51.2639999F, 49.2639999F);
                result.FillBrush = ThemeColor_Foreground_3();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_3(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 11
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_1);
                result.CenterPoint = new Vector2(20F, 20F);
                result.Offset = new Vector2(71.2639999F, 69.2639999F);
                result.FillBrush = ThemeColor_Foreground_4();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_4(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 12
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_2);
                result.CenterPoint = new Vector2(30F, 30F);
                result.Offset = new Vector2(61.2639999F, 59.2639999F);
                result.FillBrush = ThemeColor_Foreground_5();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_5(), _rootProgress);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 13
            // Path 1
            CompositionSpriteShape SpriteShape_6()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_3);
                result.CenterPoint = new Vector2(40F, 40F);
                result.Offset = new Vector2(51.2639999F, 49.2639999F);
                result.FillBrush = ThemeColor_Foreground_6();
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation_6(), _rootProgress);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // PreComp layer: Asset - AnimIcon - Action Center - Wifi
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0F, 1F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_1_0()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.516666651F, 0F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.600000024F, 1F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_1_1()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.550000012F, 0F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.633333325F, 1F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_1_2()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.583333313F, 0F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.666666687F, 1F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_0_0()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.383333325F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_0_1()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0333333351F, 1F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.416666657F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_1_to_0_2()
            {
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0666666701F, 1F, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.449999988F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(100F, 100F);
                // Scale:<0.16, 0.16>
                result.TransformMatrix = new Matrix4x4(0.159999996F, 0F, 0F, 0F, 0F, 0.159999996F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1
                shapes.Add(SpriteShape_0());
                // Layer: Layer 1
                shapes.Add(ContainerShape_0());
                // Layer: Layer 2
                shapes.Add(ContainerShape_1());
                // Layer: Layer 3
                shapes.Add(ContainerShape_2());
                // Layer: Layer 11
                shapes.Add(ContainerShape_3());
                // Layer: Layer 12
                shapes.Add(ContainerShape_4());
                // Layer: Layer 13
                shapes.Add(ContainerShape_5());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                result.InsertKeyFrame(0.333333343F, new Vector2(0.800000012F, 0.800000012F), _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.449999988F, 1F)));
                result.InsertKeyFrame(0.683333337F, new Vector2(1.10000002F, 1.10000002F), _c.CreateCubicBezierEasingFunction(new Vector2(0.550000012F, 0F), new Vector2(0.75F, 1F)));
                result.InsertKeyFrame(0.983333349F, new Vector2(1F, 1F), _c.CreateCubicBezierEasingFunction(new Vector2(0.349999994F, 0F), new Vector2(0F, 1F)));
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 1
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), StepThenHoldEasingFunction());
                result.InsertKeyFrame(0.0833333358F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.75F, new Vector2(1.10000002F, 1.10000002F), CubicBezierEasingFunction_1());
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 2
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.116666667F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.783333361F, new Vector2(1.10000002F, 1.10000002F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 3
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.150000006F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.816666663F, new Vector2(1.10000002F, 1.10000002F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 11
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.800000012F, 0.800000012F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.516666651F, new Vector2(0.800000012F, 0.800000012F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.933333337F, new Vector2(1F, 1F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 12
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_5()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.800000012F, 0.800000012F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.550000012F, new Vector2(0.800000012F, 0.800000012F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.966666639F, new Vector2(1F, 1F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // - Layer: Layer 13
            // ShapeGroup: Group 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_6()
            {
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.800000012F, 0.800000012F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.583333313F, new Vector2(0.800000012F, 0.800000012F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(1F, new Vector2(1F, 1F), _cubicBezierEasingFunction_1);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 1
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                var result = CreateVector2KeyFrameAnimation(0.75F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                var result = CreateVector2KeyFrameAnimation(0.783333361F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 3
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                var result = CreateVector2KeyFrameAnimation(0.816666663F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 11
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                var result = CreateVector2KeyFrameAnimation(0.516666651F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 12
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_4()
            {
                var result = CreateVector2KeyFrameAnimation(0.550000012F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // - PreComp layer: Asset - AnimIcon - Action Center - Wifi
            // Layer: Layer 13
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_5()
            {
                var result = CreateVector2KeyFrameAnimation(0.583333313F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            internal AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(16F, 16F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
